# Generated by Django 6.0.4 on 2026-07-07 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='inventory.category'),
        ),
        migrations.AddField(
            model_name='expense',
            name='source',
            field=models.CharField(choices=[('ocr', 'OCR Scan'), ('manual', 'Manual Entry')], default='manual', max_length=20),
        ),
    ]
