# Generated by Django 6.0.4 on 2026-09-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_auto_decrement_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='change_type',
            field=models.CharField(choices=[('purchased', 'Purchased'), ('restocked', 'Restocked'), ('consumed', 'Consumed'), ('wasted', 'Wasted'), ('adjusted', 'Adjusted')], max_length=20),
        ),
    ]
